sudo: required
language: python
python:
  - 3.6.5
install:
  - pip install pipenv
  - pipenv install --system --ignore-pipfile
script:
  - python app/manage.py test
before_install:
  - openssl aes-256-cbc -K $encrypted_fca5cae3c5db_key -iv $encrypted_fca5cae3c5db_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
