sudo: required

services:
  - docker

language: python
python:
  - 3.6.6

install:
  - pip install pipenv
  - pipenv install --system --ignore-pipfile
  - pipenv install awscli --system --ignore-pipfile
  - sudo apt-get install jq
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy

script:
  - python app/manage.py test

after_success:
  - bash .bin/ecr_credentials.sh
  - bash .bin/docker_push.sh
  - bash .bin/ecs_deploy.sh