# Generated by Django 2.2.1 on 2019-05-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugschart',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
